### PR TITLE
Update dependencies and devDependencies

### PR DESCRIPTION
**Pull request by shinnn**
* I updated dependencies and devDependencies.
  * [gulp-browserify is blacklisted](https://github.com/gulpjs/plugins/issues/47). We should use [broswerify](https://github.com/substack/node-browserify) module directly in gulpfile.
  * I replaced [async](https://github.com/caolan/async) with [async-each-series](https://github.com/jb55/async-each-series). We should choose smaller modules.
* I removed `.npmignore`. It's not necessary because package.json has `files` field.

### CODE REVIEW

**Comment by shakyShane** [comment]
Welcome @shinnn to BrowserSync/UI :)

**Comment by shinnn** [comment]
> Welcome @shinnn to BrowserSync/UI :)

I'd happily help maintain and improve browser-sync related modules if you could add me to BrowserSync org :)

**Comment by shakyShane** [comment]
Welcome to the team @shinnn

**Comment by shinnn** [comment]
Yay, thank you for your invitation!

**Comment by shakyShane** [comment]
No problem! 

I'm slowing moving all BrowserSync repos over to this org so you'll have write-access to each as they come over :)

**Pull request merged**
