### PR TITLE
Clean package.json and dependencies

### PR DESCRIPTION
**Pull request by Siilwyn**
By cleaning the package.json and updating the dependencies this fixes the Travis build from failing.
:sparkles:

### CODE REVIEW

**Comment by shakyShane** [comment]
Wow! thank you, I will look at merging this asap :)

**Comment by Siilwyn** [comment]
:smiley: No problem, looking forward to the merge! Take your time to test though I've been quite blunt at updating all dependencies except from `jshint`.

**Comment by shakyShane** [comment]
:+1: :star:

**Comment by shakyShane** [comment]
Your changes are in - I had to rebase/merge manually as I screwed up and had local commit not on GH. Anyway, merged and published at browser-sync-ui@0.5.17

Thank you for your time :)

**Pull request closed without merging**
